### ISSUE TITLE
邻接矩阵

### ISSUE THREAD

**Issue by 11051911** [yueliu1999/DCRN#12]
你好，可以提供一下创建邻接矩阵的代码吗？

**Comment by yueliu1999** [comment]
你好，感谢关注~。创建邻接矩阵的话只需要将自己的数据里面的邻接矩阵保存为numpy的npy文件再load即可。

**Comment by 11051911** [comment]
> 你好，感谢关注~。创建邻接矩阵的话只需要将自己的数据里面的邻接矩阵保存为numpy的npy文件再load即可。

代码中的邻接矩阵的值只能是1或者是整数吗
Traceback (most recent call last):
  File "F:\论文中的程序\DCRN-main\DCRN_pretrain\pretrain_ae\main.py", line 97, in <module>
    x, y, adj = load_graph_data(args.name, show_details=True)
  File "F:\论文中的程序\DCRN-main\DCRN_pretrain\pretrain_ae\main.py", line 57, in load_graph_data
    for i in range(max(label)+1):
TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by yueliu1999** [comment]
邻接矩阵里面的值不一定只能是1或整数。

你现在的这个错误看起来像是label的问题。
